# Generated by Django 5.1 on 2024-09-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('boolean', 'Yes or No'), ('text', 'Short answer'), ('choices', 'Choices')], max_length=10),
        ),
    ]
