# Generated by Django 5.1 on 2024-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_screen_time',
            field=models.DecimalField(decimal_places=2, help_text='Hours', max_digits=10),
        ),
    ]
