# Generated by Django 5.1 on 2024-09-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0002_alter_profile_avg_screen_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avg_screen_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hours', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
