# Generated by Django 5.1 on 2024-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0004_alter_profile_age_alter_profile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
